-- Charm Avenue — seed data
-- Run this AFTER schema.sql, once, to carry over the current hardcoded catalog
-- so the storefront keeps looking identical right after cutover.

insert into categories (slug, title, subtitle, emoji, tag, image, image_alt, tag_bg, tag_text, description, sort_order) values
('jewellery', 'Anti-Tarnish Jewellery', 'Rings · Bracelets · Neckchains · Watches', '💍', 'Best Seller',
 'https://images.unsplash.com/photo-1621311628038-01cd988520c2',
 'Gold and silver rings and bracelets laid on a pink marble surface, warm feminine jewellery flat lay',
 '#E8828F', '#FFFFFF',
 'Jewellery that stays as pretty as day one. Every piece is anti-tarnish coated so your rings, bracelets and neckchains keep their shine wear after wear.',
 1),
('hair', 'Kawaii Hair Accessories', 'Claw Clips · Scrunchies · Skincare Bands', '🎀', 'Trending',
 'https://img.rocket.new/generatedImages/rocket_gen_img_18ed727e8-1772212936132.png',
 'Colourful scrunchies and claw clips arranged on a pastel pink background, hair accessories flatlay',
 '#D1636F', '#FFFFFF',
 'Cute, comfy hair essentials for everyday and every mood — from gentle satin scrunchies to statement claw clips.',
 2),
('makeup', 'Cute Makeup', 'Lip Glosses · Beauty Blenders · Nail Extensions', '💄', 'New In',
 'https://img.rocket.new/generatedImages/rocket_gen_img_103b67372-1767194170606.png',
 'Pink and nude lip glosses and makeup brushes on a white vanity, feminine beauty product flatlay',
 '#F6D3D6', '#1E1712',
 'Playful makeup finds that make getting ready the best part of your day — glossy, glittery, always cute.',
 3),
('accessories', 'Trending Accessories', 'Bag Charms · Coin Pouches · Keycuties · Plushies', '🧸', 'Viral',
 'https://images.unsplash.com/photo-1671602391194-3be89fb687dc',
 'Pastel mini bags and plush charms on a lavender background, cute kawaii accessories',
 '#B85864', '#FFFFFF',
 'The little extras that make an outfit — viral bag charms, mini wallets and plushies to clip onto everything.',
 4),
('pouches', 'Organiser Pouches', 'Jewellery Cases · Makeup Bags · Travel Kits', '👜', 'Gift Ready',
 'https://images.unsplash.com/photo-1591375372245-6d76eb0531cd',
 'Pink and floral zippered pouches and cosmetic bags arranged on a light background, gift-ready organiser',
 '#D1636F', '#FFFFFF',
 'Keep your charm collection tidy and gift-ready with our zippered pouches, jewellery cases and travel kits.',
 5)
on conflict (slug) do nothing;

insert into products (slug, name, category_slug, price, original_price, image, image_alt, tag, tag_bg, tag_text, emoji, description, rating, review_count) values
('p1', 'Dainty Star Ring', 'jewellery', 299, 499,
 'https://images.unsplash.com/photo-1721103428007-8d466bf9ee00',
 'Delicate gold star ring on a soft pink background, anti-tarnish finish',
 'Hot 🔥', '#E8828F', '#FFFFFF', '⭐',
 'A dainty star-shaped ring in warm gold-tone anti-tarnish plating. Adjustable band fits most sizes, perfect for everyday stacking or gifting.',
 4.8, 214),
('p2', 'Butterfly Claw Clip', 'hair', 199, null,
 'https://img.rocket.new/generatedImages/rocket_gen_img_14860b929-1772356988721.png',
 'Pastel butterfly claw clip on a lavender background, cute hair accessory',
 'Trending', '#D1636F', '#FFFFFF', '🦋',
 'A pastel butterfly claw clip with a strong grip and gentle teeth that won''t snag your hair. Great for thick or thin hair alike.',
 4.7, 168),
('p3', 'Glossy Lip Set (3pc)', 'makeup', 449, 699,
 'https://images.unsplash.com/photo-1570088727237-68500d217455',
 'Three sheer pink lip glosses on a white surface, cute makeup product',
 'New In ✨', '#F6D3D6', '#1E1712', '💄',
 'A set of three sheer, non-sticky lip glosses in wearable pink shades — buildable colour with a glassy, hydrating finish.',
 4.9, 302),
('p4', 'Mini Teddy Bag Charm', 'accessories', 349, null,
 'https://images.unsplash.com/photo-1724645550639-0dd96a8fca5d',
 'Tiny plush teddy bear bag charm in pastel pink, kawaii accessory',
 'Viral 🧸', '#D1636F', '#FFFFFF', '🧸',
 'A tiny plush teddy bear charm with a secure clip, ready to hang on your bag, backpack or keychain.',
 4.6, 97),
('p5', 'Pearl Drop Bracelet', 'jewellery', 499, 799,
 'https://images.unsplash.com/photo-1638332746343-b8494c8f5dce',
 'Delicate pearl bracelet with gold accents on a pink marble surface',
 'Best Seller', '#E8828F', '#FFFFFF', '🤍',
 'Freshwater-style pearl drops on a gold-tone anti-tarnish chain, with an adjustable extender for the perfect fit.',
 4.9, 256),
('p6', 'Floral Organiser Pouch', 'pouches', 649, 999,
 'https://images.unsplash.com/photo-1502463471782-7626cbfc7d2b',
 'Pink floral zippered pouch on a cream background, organiser bag',
 'Gift ❤️', '#D1636F', '#FFFFFF', '🌸',
 'A floral zippered pouch with internal compartments — perfect for keeping jewellery, makeup or travel essentials tangle-free.',
 4.8, 134),
('p7', 'Satin Scrunchie Set', 'hair', 249, null,
 'https://images.unsplash.com/photo-1586212699614-73a87e6c79e0',
 'Set of satin scrunchies in pastel colours on a pink background',
 null, null, null, '🎀',
 'A set of soft satin scrunchies in pastel shades, gentle on hair with no creasing — great for everyday wear or sleeping in.',
 4.7, 189),
('p8', 'Crystal Neck Chain', 'jewellery', 799, 1299,
 'https://images.unsplash.com/photo-1708222169717-8251cfdfa608',
 'Delicate crystal pendant necklace on a soft white background, anti-tarnish jewellery',
 'Premium 💎', '#B85864', '#FFFFFF', '💎',
 'A crystal pendant on a fine anti-tarnish chain — dainty enough for daily wear, sparkly enough for a night out.',
 4.9, 178),
('p9', 'Gel Nail Extension Kit', 'makeup', 899, 1499,
 'https://img.rocket.new/generatedImages/rocket_gen_img_1f04ffe3e-1767084611690.png',
 'Pink and nude gel nail extension kit spread on a white surface',
 'DIY Kit', '#F6D3D6', '#1E1712', '💅',
 'An at-home gel nail extension kit with everything you need for a salon-style manicure — no appointment needed.',
 4.5, 88)
on conflict (slug) do nothing;
